import { AUTHOR } from "../data/authorInfo";

/**
 * Draws the author/disclaimer footer on every page of a jsPDF document.
 * Call once, after all content is drawn and before doc.save().
 * Uses only ASCII characters (standard jsPDF fonts render others badly).
 * Sizes are given in millimetres and converted, so it works whatever
 * unit the document was created with.
 */
export function addPdfFooter(doc) {
  const mm = (v) => (v * 2.834645669) / doc.internal.scaleFactor;

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = mm(14);

  const who = AUTHOR.name ? `${AUTHOR.name}, a student` : "a student";
  const text =
    `Disclaimer: This report was generated by an application developed by ${who} ` +
    `at ${AUTHOR.university} (Student ID: ${AUTHOR.studentId}) as part of an ` +
    `academic thesis project. Results are model based estimates for academic ` +
    `and research purposes only and are not financial, investment, economic, ` +
    `or policy advice.`;

  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);

    doc.setDrawColor(203, 213, 225);
    doc.setLineWidth(mm(0.2));
    doc.line(margin, pageH - mm(17), pageW - margin, pageH - mm(17));

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    const lines = doc.splitTextToSize(text, pageW - margin * 2);
    doc.text(lines, margin, pageH - mm(13));
  }
}  